#데이터 분석 예시
SELECT * from fish;
SELECT * FROM FISH WHERE FIS_ADDR LIKE '홍천%' AND FIS_NUM IN(1); #홍천에서 잡은내용
SELECT * FROM FISH WHERE FIS_SPEC LIKE '쏘가리%'; #쏘가리 잡은곳
SELECT * FROM FISH WHERE FIS_SIZE IN(50); # 50사이즈가 잡힌곳
SELECT * FROM FISH WHERE FIS_ADDR LIKE '인제%' AND FIS_NUM BETWEEN 5 AND 30; #인제에서 5마리이상 30마리이하 잡힌내용
SELECT * FROM FISH WHERE FIS_SPEC LIKE '꺽지%' GROUP BY FIS_SPEC; #GROUP BY DISTICT(최대값,최솟값,평균등을 구하는 함수)
SELECT FIS_ADDR, FIS_NUM FROM FISH GROUP BY FIS_ADDR, FIS_NUM ORDER BY 2 DESC; #제일 많이 잡힌곳
SELECT FIS_ADDR, FIS_SIZE FROM FISH GROUP BY FIS_ADDR, FIS_SIZE ORDER BY 2 DESC; #제일 크게 잡힌 곳
SELECT FIS_ADDR, FIS_NUM, FIS_SIZE FROM FISH GROUP BY FIS_ADDR, FIS_NUM, FIS_SIZE ORDER BY 3 DESC; #제일 크게잡혔는데,몇마리 잡혔는지?
SELECT DISTINCT FIS_ADDR FROM FISH WHERE FIS_SPEC ='베스' ORDER BY 1; #베스가 잡힌곳, 중복제거
SELECT FIS_SPEC, FIS_NUM FROM FISH GROUP BY FIS_NUM ORDER BY 2 DESC; # 가장 많이 잡힌 어종
SELECT FIS_SPEC, FIS_SIZE FROM FISH GROUP BY FIS_SIZE ORDER BY 2 DESC; # 가장 크게 잡힌 어종
SELECT FIS_SPEC, FIS_SIZE, FIS_NUM, FIS_ADDR FROM FISH WHERE FIS_SIZE >=40 AND FIS_NUM >=10 ORDER BY 4 DESC; #크게 잡히면서 많이 잡은곳

#grant all on mysql.* to db_test@localhost

#해양청 실측조류 데이터 
CREATE TABLE tidalcurrent (
	OBS_TIME DATETIME NULL DEFAULT NULL,
	current_direct FLOAT(12) NULL DEFAULT NULL,
	current_speed FLOAT(12) NULL DEFAULT NULL,
	OBS_POST_NAME VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	LAT FLOAT(12) NULL DEFAULT NULL,
	LON FLOAT(12) NULL DEFAULT NULL
)
ENGINE=INNODB DEFAULT CHARSET=utf8;

#해양청 실측풍향 테이블 생성
CREATE TABLE wind (
	record_time DATETIME NULL DEFAULT NULL,
	wind_dir FLOAT(12) NULL DEFAULT NULL,
	wind_speed FLOAT(12) NULL DEFAULT NULL,
	OBS_POST_NAME VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	LAT FLOAT(12) NULL DEFAULT NULL,
	LON FLOAT(12) NULL DEFAULT NULL
)
ENGINE=INNODB DEFAULT CHARSET=UTF8;

SELECT * FROM wind;

#해양청 실측파고 테이블 생성
CREATE TABLE wave (
	record_time DATETIME NULL DEFAULT NULL,
	wave_height FLOAT(12) NULL DEFAULT NULL,
	OBS_POST_NAME VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	LAT FLOAT(12) NULL DEFAULT NULL,
	LON FLOAT(12) NULL DEFAULT NULL
)
ENGINE=INNODB DEFAULT CHARSET=UTF8;

SELECT * FROM wave;

#해양청 실측조위 테이블 생성
CREATE TABLE tidelevel (
	record_time DATETIME NULL DEFAULT NULL,
	tide_level FLOAT(12) NULL DEFAULT NULL,
	OBS_POST_NAME VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	LAT FLOAT(12) NULL DEFAULT NULL,
	LON FLOAT(12) NULL DEFAULT NULL
)
ENGINE=INNODB DEFAULT CHARSET=UTF8;

SELECT * FROM tidelevel;

#해양청 실측수온 테이블 생성
CREATE TABLE temp (
	record_time DATETIME NULL DEFAULT NULL,
	water_temp FLOAT(12) NULL DEFAULT NULL,
	OBS_POST_NAME VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	LAT FLOAT(12) NULL DEFAULT NULL,
	LON FLOAT(12) NULL DEFAULT NULL
)
ENGINE=INNODB DEFAULT CHARSET=UTF8;

SELECT * FROM temp;

#해양청 
CREATE TABLE tidalpre (
	tph_level INT NULL DEFAULT NULL,
	tph_time DATETIME NULL DEFAULT NULL,
	OBS_POST_NAME VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	LAT FLOAT(12) NULL DEFAULT NULL,
	LON FLOAT(12) NULL DEFAULT NULL,
	hl_code VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_general_ci'
)
ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE tidalpre;

SELECT * FROM tidalpre;

#기상청 육상예보 테이블 생성
CREATE TABLE ASOS (
	regld VARCHAR(30) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	tm DATETIME NULL DEFAULT NULL,
	avgTa FLOAT(12)  NULL DEFAULT NULL,
	minTa FLOAT(12) NULL DEFAULT NULL,
	minTaHrmt FLOAT(12) NULL DEFAULT NULL,
	maxTa FLOAT(12) NULL DEFAULT NULL,
	maxTaHrmt FLOAT(12) NULL DEFAULT NULL,
	hr1MaxRn FLOAT(12) NULL DEFAULT NULL,
	hr1MaxRnHrmt FLOAT(12) NULL DEFAULT NULL,
	sumRn FLOAT(12) NULL DEFAULT NULL,
	maxWs FLOAT(12) NULL DEFAULT NULL,
	maxWsWd FLOAT(12) NULL DEFAULT NULL,
	maxWsHrmt FLOAT(12) NULL DEFAULT NULL,
	avgWs FLOAT(12) NULL DEFAULT NULL,
	maxWd FLOAT(12) NULL DEFAULT NULL,
	avgTd FLOAT(12) NULL DEFAULT NULL,
	minRhm FLOAT(12) NULL DEFAULT NULL,
	minRhmHrmt FLOAT(12) NULL DEFAULT NULL,
	avgRhm FLOAT(12) NULL DEFAULT NULL,
	ssumSsHr FLOAT(12) NULL DEFAULT NULL,
	hr1MaxIcsrHrmt FLOAT(12) NULL DEFAULT NULL,
	hr1MaxIcsr FLOAT(12) NULL DEFAULT NULL,
	sumGsr FLOAT(12) NULL DEFAULT NULL,
	sumfogdur FLOAT(12) NULL DEFAULT NULL
)
ENGINE=INNODB DEFAULT CHARSET=UTF8;

# set @@global.sql_mode = "ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"

DROP TABLE asos;

CREATE TABLE Meteorological (
	regld VARCHAR(50) NULL DEFAULT NULL,
	LAT FLOAT(12) NULL DEFAULT NULL,
	LON FLOAT(12) NULL DEFAULT NULL,
	regName VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci'
)
ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE meteorological;

SELECT * FROM meteorological;

CREATE TABLE discharge (
	WL_OBS_CD VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	OBS_YMD DATE NULL DEFAULT NULL,
	OBS_STHM VARCHAR(50) NULL DEFAULT NULL,
	AVG_WL FLOAT(12) NULL DEFAULT NULL,
	RIV_WITH FLOAT(12) NULL DEFAULT NULL,
	C_ARE FLOAT(12) NULL DEFAULT NULL,
	W_SPD FLOAT(12) NULL DEFAULT NULL,
	FLW FLOAT(12) NULL DEFAULT NULL,
	OBS_WAY VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci'
)
ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE discharge;

CREATE TABLE weathertime (
	ymdh DATETIME NULL DEFAULT NULL,
	ta FLOAT(12) NULL DEFAULT NULL,
	hm FLOAT(12) NULL DEFAULT NULL,
	td FLOAT(12) NULL DEFAULT NULL,
	ps FLOAT(12) NULL DEFAULT NULL,
	ws FLOAT(12) NULL DEFAULT NULL,
	sihr1 FLOAT(12) NULL DEFAULT NULL,
	catot FLOAT(12) NULL DEFAULT NULL,
	sdtot FLOAT(12) NULL DEFAULT NULL,
	sshr1 FLOAT(12) NULL DEFAULT NULL,
	obscd_time INT NULL DEFAULT NULL
)
ENGINE=INNODB DEFAULT CHARSET=UTF8;
